version: '3.6'
networks:
  web: {external: true}

services:
  some_service:
    image: containous/whoami
    networks: [web]

    deploy:
      labels:
        - traefik.http.services.some_service.loadbalancer.server.port=80
        - traefik.http.routers.some_service.tls.certresolver=le

        # optional: - traefik.http.routers.some_service.rule=Host(`some-name.example.com`)
        # otherwise it will become `https://${docker_stack_name}-${yaml_service_name}.universesapi.com`

